#Uncomment and set to the path of the Gradle plugins if they are not in niagara_home
#gradlePluginHome=

#The path to the installation of Niagara you are building against
niagara_home=c:\\niagara\\niagara-4.15.1.16

#The path to niagara_user_home for the version of Niagara you are building against
niagara_user_home=C:\\Users\\Richard McElhinney\\Niagara4.15\\tridium

#Uncomment and set to the path of your node install if you are building JavaScript
#modules
#nodeHome=

#NOTE: Niagara builds _require_ a full JDK. You can see what toolchains Gradle can
#find automatically by running
#
#  "gradlew -q javaToolchains -Porg.gradle.java.installations.auto-detect=true".
#
#If that list includes a valid Java 8 JDK, you can leave the following three
#properties commented out and let Gradle select a JDK automatically. If it does not,
#you can set the 'org.gradle.java.installations.paths' property to the full path to
#a Java 8 JDK

#org.gradle.java.installations.auto-detect=true
#org.gradle.java.installations.auto-download=false

#org.gradle.java.installations.paths=
