//
// Copyright (c) 2012, J2 Innovations
// Licensed under the Academic Free License version 3.0
//
// History:
//   06 Feb 2013  Mike Jarmy  Creation
//

package nhaystack.site;

import javax.baja.sys.*;
import javax.baja.util.*;

import haystack.*;
import nhaystack.*;

/**
 *  BHEquip represents a Haystack 'equip' rec.
 */
public class BHEquip extends BHTagged
{
    /*-
    class BHEquip
    {
        properties
        {
            haystackNav: BFormat default{[ BFormat.make("%parent.name%") ]}
        }
    }
    -*/
/*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
/*@ $nhaystack.site.BHEquip(408458736)1.0$ @*/
/* Generated Sun Feb 10 10:55:18 EST 2013 by Slot-o-Matic 2000 (c) Tridium, Inc. 2000 */

////////////////////////////////////////////////////////////////
// Property "haystackNav"
////////////////////////////////////////////////////////////////
  
  /**
   * Slot for the <code>haystackNav</code> property.
   * @see nhaystack.site.BHEquip#getHaystackNav
   * @see nhaystack.site.BHEquip#setHaystackNav
   */
  public static final Property haystackNav = newProperty(0, BFormat.make("%parent.name%"),null);
  
  /**
   * Get the <code>haystackNav</code> property.
   * @see nhaystack.site.BHEquip#haystackNav
   */
  public BFormat getHaystackNav() { return (BFormat)get(haystackNav); }
  
  /**
   * Set the <code>haystackNav</code> property.
   * @see nhaystack.site.BHEquip#haystackNav
   */
  public void setHaystackNav(BFormat v) { set(haystackNav,v,null); }

////////////////////////////////////////////////////////////////
// Type
////////////////////////////////////////////////////////////////
  
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BHEquip.class);

/*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

    public EquipNavId makeNavId(SiteNavId siteNav)
    {
        return EquipNavId.make(
            siteNav.getSiteName(),
            getHaystackNav().format(this));
    }

    /**
      * Return default values for those tags which are essential for
      * defining this component.
      */
    public HDict getDefaultEssentials()
    {
        return ESSENTIALS;
    }
  
    /**
      * Generate all the tags for this component, including
      * autogenerated tags like "id", and any other tags 
      * defined in the 'haystack' property.
      */
    public HDict generateTags()
    {
        HDictBuilder hdb = new HDictBuilder();

        // add annotated
        hdb.add(getHaystack().getDict());

        // add id and equip
        hdb.add("id", NHRef.make(this).getHRef());
        hdb.add("equip");

        // add misc other tags
        String dis = getDisplayName(null);
        if (dis != null) hdb.add("dis", dis);
        hdb.add("axType", getType().toString());
        hdb.add("axSlotPath", getSlotPath().toString());

        return hdb.toDict();
    }

    public BIcon getIcon() { return ICON; }

////////////////////////////////////////////////////////////////
// Attributes
////////////////////////////////////////////////////////////////

    private static final BIcon ICON = BIcon.make("module://nhaystack/nhaystack/icons/equip.png");

    private static final HDict ESSENTIALS;
    static
    {
        HDictBuilder hd = new HDictBuilder();
        hd.add("siteRef", HRef.make("null"));
        ESSENTIALS = hd.toDict();
    }
}

